### ISSUE TITLE
Migrate to Github-Project

### ISSUE THREAD

**Issue by NSpalek** [fiware-austria/SCDP#100]

**Comment by AnotherCodeArtist** [comment]
Github project created but should be moved to fiware-austria/IPPR...

**Comment by amarbajric** [comment]
Because the original repo was forked by the `fiware-austria` account, I would also suggest to migrate all issues to the according repository.

There are some options available on how to migrate issues from one repo to another:
- GH's [official (beta) solution](https://help.github.com/en/articles/transferring-an-issue-to-another-repository#transferring-an-open-issue-to-another-repository) for migrating issues between repos
- [Unofficial Python script](https://github.com/IQAndreas/github-issues-import) that seems to also work
