### ISSUE TITLE
Adoption of Dual-Chart Dashboard

### ISSUE THREAD

**Issue by AnotherCodeArtist** [fiware-austria/SCDP#105]
Currently the dual-chart dashboard forces aggregation. 
However, it should also allow for un-aggregated time-series using begin/end and limit/offset.

Besides this, #104 will bring a new aggregation period

**Comment by stfnltnr** [comment]
New Version of the Dual-Chart Dashboard is online for review and testing at Workspace [stefan/REVIEW-DualChart-Limit](http://i101v180.intra.graz.at:30082/stefan/review-dualchart-limit#view=workspace&tab=tab)

Added new fields to the dual-chart input widget and modified the dual-chart operator to query 
- max number of data points - Max Data Points
- number of data points aggregated over a period of time - Max Data Points & Aggregation Method
- aggregated data (month, hour, day) - Aggregation Period and Aggregation Method

Due to the implementation of GoogleCharts and the fact that in most cases timestamps from two different sensors aren't identical the data points are not connected as they are via aggregated data queries. The example below shows how 10 values from Sensor1 and Sensor7 are passed to the GoggleChart.
```
{
  "type": "LineChart",
  "options": {
    "title": "Sensor1 & Sensor7 (10 Werte)",
 .........
 "data": [
    [ "Time", "Luftdruck - Sensor1", "Luftdruck - Sensor7" ],
    [ "2019-04-17 00:00:24", null, 978.27 ],
    [ "2019-04-17 00:00:25", 974.43, null ],
    [ "2019-04-17 00:00:54", null, 978.29 ],
    [ "2019-04-17 00:00:55", 974.45, null ],
    [ "2019-04-17 00:01:24", null, 978.29 ],
    [ "2019-04-17 00:01:25", 974.43, null ],
    [ "2019-04-17 00:01:54", null, 978.31 ],
    [ "2019-04-17 00:01:55", 974.45, null ],
    [ "2019-04-17 00:02:24", null, 978.29 ],
    [ "2019-04-17 00:02:25", 974.45, null ],
    [ "2019-04-17 00:02:54", null, 978.31 ],
    [ "2019-04-17 00:02:55", 974.45, null ],
    [ "2019-04-17 00:03:24", null, 978.31 ],
    [ "2019-04-17 00:03:25", 974.47, null ],
    [ "2019-04-17 00:03:54", null, 978.31 ],
    [ "2019-04-17 00:03:55", 974.47, null ],
    [ "2019-04-17 00:04:24", null, 978.29 ],
    [ "2019-04-17 00:04:25", 974.47, null ],
    [ "2019-04-17 00:04:54", null, 978.31 ],
    [ "2019-04-17 00:04:55", 974.45, null ]
]}

**Comment by stfnltnr** [comment]
added new aggregation periods `week`, `halfhour` and `quarterhour`.  (#104)

**Comment by stfnltnr** [comment]
remove await from getSensorData functions
