### ISSUE TITLE
Node-Red Flow for Hadoop file manipulation (Mobility Insights)

### ISSUE THREAD

**Issue by apruitg** [fiware-austria/SCDP#138]
Node-Red Flow for easy creation and deletion of files in Hadoop-FS for Mobility Insights.

Estimated number of files at the moment: 39

**Comment by stfnltnr** [comment]
Due to the new implementation of the Hadoop HA two possible namenodes (nn1,nn2) are available for processing data. Data must be sent to the active namenode. If a namenode is in active or in standby mode could be determined by sending a `GET` request to the following URL

- nn1: `http://hadoop-namenode-0.hadoop-namenode.hadoop-ha.svc.cluster.local:9870/isActive`
- nn2: `http://hadoop-namenode2-0.hadoop-namenode2.hadoop-ha.svc.cluster.local:9870/isActive`

An active namenode returns status code `200 OK` while a node in standby mode returns `405 I am not Active!`

External URLs:
- nn1: `http://10.1.101.180:31987/isActive`
- nn2: `http://10.1.101.180:31988/isActive`
