### ISSUE TITLE
Kubernetes Config Files on Github

### ISSUE THREAD

**Issue by buchsbau13** [fiware-austria/SCDP#35]
yaml files

**Comment by AnotherCodeArtist** [comment]
Since the deployment of fiware and mongo is now controlled via helm, changes should be managed via the [fiware production values file](https://github.com/fiware-austria/IPPR-GettingSmart/blob/master/KubernetesInfrastructure/FIWARE-Helm/fiware/values-itg-cluster.yaml).
A similar approach will soon become available for Hadoop via #92.
